/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cellAction;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Jayjay
 */
public class currentOrderPanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public currentOrderPanelAction() {
        initComponents();
    }

    public void initEvent (TableActionEvent event, int row){
        cmdView.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed (ActionEvent ae){
                event.onView(row);
            }
        });
        cmdDelete.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed (ActionEvent ae){
                event.onDelete(row);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdDelete = new cellAction.ActionButton();
        cmdView = new cellAction.ActionButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        add(cmdDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 30));

        cmdView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        add(cmdView, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cellAction.ActionButton cmdDelete;
    private cellAction.ActionButton cmdView;
    // End of variables declaration//GEN-END:variables

    
}
