/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminSubWindow;

import AdminBranch.AdminMain;
import databaseConnection.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Laurence
 */
public class SalesReport extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement sqlPST = null;
    ResultSet sqlResult = null;
    
    public SalesReport() {
        initComponents();
        conn = DBConnection.connectionDB();
        
        updateLabelsforReport();
        infoPanel.setBackground(new java.awt.Color(0, 0, 0, 80));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        totalSales = new javax.swing.JLabel();
        pastrySales = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        totalOrders = new javax.swing.JLabel();
        coffeeCount = new javax.swing.JLabel();
        teaCount = new javax.swing.JLabel();
        frappeCount = new javax.swing.JLabel();
        pastryCount = new javax.swing.JLabel();
        coffeeSales = new javax.swing.JLabel();
        teaSales = new javax.swing.JLabel();
        frappeSales = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Confirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        infoPanel.setBackground(new java.awt.Color(0, 0, 0));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(111, 68, 54));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sales");
        infoPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(226, 186, 171));
        jPanel7.setPreferredSize(new java.awt.Dimension(550, 30));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        infoPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 550, 10));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Orders");
        infoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        totalSales.setBackground(new java.awt.Color(255, 255, 255));
        totalSales.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalSales.setForeground(new java.awt.Color(255, 255, 255));
        totalSales.setText("10");
        infoPanel.add(totalSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, -1, -1));

        pastrySales.setBackground(new java.awt.Color(255, 255, 255));
        pastrySales.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pastrySales.setForeground(new java.awt.Color(255, 255, 255));
        pastrySales.setText("P1000");
        infoPanel.add(pastrySales, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sales Report");
        infoPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 73, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Orders Served:");
        infoPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Pastry");
        infoPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel20.setBackground(new java.awt.Color(111, 68, 54));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total Sales:");
        infoPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Coffee");
        infoPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Tea");
        infoPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Frappe");
        infoPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        totalOrders.setBackground(new java.awt.Color(255, 255, 255));
        totalOrders.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalOrders.setForeground(new java.awt.Color(255, 255, 255));
        totalOrders.setText("10");
        infoPanel.add(totalOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        coffeeCount.setBackground(new java.awt.Color(255, 255, 255));
        coffeeCount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        coffeeCount.setForeground(new java.awt.Color(255, 255, 255));
        coffeeCount.setText("10");
        infoPanel.add(coffeeCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        teaCount.setBackground(new java.awt.Color(255, 255, 255));
        teaCount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        teaCount.setForeground(new java.awt.Color(255, 255, 255));
        teaCount.setText("10");
        infoPanel.add(teaCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        frappeCount.setBackground(new java.awt.Color(255, 255, 255));
        frappeCount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        frappeCount.setForeground(new java.awt.Color(255, 255, 255));
        frappeCount.setText("10");
        infoPanel.add(frappeCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        pastryCount.setBackground(new java.awt.Color(255, 255, 255));
        pastryCount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pastryCount.setForeground(new java.awt.Color(255, 255, 255));
        pastryCount.setText("10");
        infoPanel.add(pastryCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        coffeeSales.setBackground(new java.awt.Color(255, 255, 255));
        coffeeSales.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        coffeeSales.setForeground(new java.awt.Color(255, 255, 255));
        coffeeSales.setText("P1000");
        infoPanel.add(coffeeSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        teaSales.setBackground(new java.awt.Color(255, 255, 255));
        teaSales.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        teaSales.setForeground(new java.awt.Color(255, 255, 255));
        teaSales.setText("P1000");
        infoPanel.add(teaSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        frappeSales.setBackground(new java.awt.Color(255, 255, 255));
        frappeSales.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        frappeSales.setForeground(new java.awt.Color(255, 255, 255));
        frappeSales.setText("P1000");
        infoPanel.add(frappeSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(226, 186, 171));
        jPanel8.setPreferredSize(new java.awt.Dimension(550, 30));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        infoPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 550, 10));

        Confirm.setBackground(new java.awt.Color(111, 68, 54));
        Confirm.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Confirm.setForeground(new java.awt.Color(255, 255, 255));
        Confirm.setText("Confirm");
        Confirm.setBorderPainted(false);
        Confirm.setContentAreaFilled(false);
        Confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfirmMouseExited(evt);
            }
        });
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SalesReport.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="EVENTS"> 
    private void ConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmMouseEntered
        // TODO add your handling code here:
        Confirm.setContentAreaFilled(true);
        Confirm.setBackground(new Color(111, 68, 54));
        Confirm.setForeground(Color.white);

    }//GEN-LAST:event_ConfirmMouseEntered

    private void ConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmMouseExited
        // TODO add your handling code here:
        Confirm.setContentAreaFilled(false);
        Confirm.setForeground(Color.white);

    }//GEN-LAST:event_ConfirmMouseExited

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        // TODO add your handling code here:
        callAdminMain();
        setVisible(false);
    }//GEN-LAST:event_ConfirmActionPerformed

    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="FUNTIONALITIES"> 
    private void updateLabelsforReport(){
        String coffeeString = Integer.toString(countByCategory("coffee"));
        String teaString = Integer.toString(countByCategory("tea"));
        String frappeString = Integer.toString(countByCategory("frappe"));
        String pastryString = Integer.toString(countByCategory("pastry"));
        coffeeCount.setText(coffeeString);
        teaCount.setText(teaString);
        frappeCount.setText(frappeString);
        pastryCount.setText(pastryString);
        String coffeeAmountText = Integer.toString(addByCategory("coffee"));
        String teaAmountText = Integer.toString(addByCategory("tea"));
        String frappeAmountText = Integer.toString(addByCategory("frappe"));
        String pastryAmountText = Integer.toString(addByCategory("pastry"));
        coffeeSales.setText("₱" +coffeeAmountText);
        teaSales.setText("₱" +teaAmountText);
        frappeSales.setText("₱" +frappeAmountText);
        pastrySales.setText("₱" +pastryAmountText);
        String totalCountString = Integer.toString(totalCount(countByCategory("coffee"),countByCategory("tea"),countByCategory("frappe"),countByCategory("pastry")));
        String totalAmountString = Integer.toString(totalCount(addByCategory("coffee"),addByCategory("tea"),addByCategory("frappe"),addByCategory("pastry")));
        totalOrders.setText(totalCountString);
        totalSales.setText("₱" + totalAmountString);
    }
    private int totalCount(int cat1, int cat2, int cat3, int cat4){
        int total = cat1 + cat2 + cat3 + cat4;
        return total;
    }
    private int addByCategory(String category){
        int categoryAmount = 0;
        String sqlQuery = "SELECT Category, Sales FROM SalesByProducts WHERE LOWER(Category) = ?";
        try{
            sqlPST = conn.prepareStatement(sqlQuery);
            sqlPST.setString(1, category);
            sqlResult = sqlPST.executeQuery();
            while (sqlResult.next()){
                String categoryString = sqlResult.getString("Category").toLowerCase();
                int categorySale = sqlResult.getInt("Sales");
                if (categoryString.equals(category.toLowerCase())){
                    categoryAmount = categoryAmount + categorySale;
                }
            }
            return categoryAmount;
        }catch (SQLException e) {
            e.printStackTrace();
            return 0;
        }
    }
    private int countByCategory(String category){
        int categoryCount = 0;
        String sqlQuery = "SELECT Category FROM SalesByProducts WHERE LOWER(Category) = ?";
        try{
            sqlPST = conn.prepareStatement(sqlQuery);
            sqlPST.setString(1, category);
            sqlResult = sqlPST.executeQuery();
            while (sqlResult.next()){
                String categoryString = sqlResult.getString("Category").toLowerCase();
                if (categoryString.equals(category.toLowerCase())){
                    categoryCount++;
                }
            }
            return categoryCount;
        }catch (SQLException e) {
            e.printStackTrace();
            return 0;
        }
    }
    private void callAdminMain(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }
    // </editor-fold> 
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SalesReport().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel coffeeCount;
    private javax.swing.JLabel coffeeSales;
    private javax.swing.JLabel frappeCount;
    private javax.swing.JLabel frappeSales;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel pastryCount;
    private javax.swing.JLabel pastrySales;
    private javax.swing.JLabel teaCount;
    private javax.swing.JLabel teaSales;
    private javax.swing.JLabel totalOrders;
    private javax.swing.JLabel totalSales;
    // End of variables declaration//GEN-END:variables
}
